import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import { GeistSans } from 'geist/font/sans'
import { Header } from '@/components/header/header'
import './globals.css'

const raleway = Raleway({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'],
  variable: '--font-raleway',
  display: 'swap' // Важно для предотвращения мерцания текста
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru'>
      <body className={`${raleway.variable} ${GeistSans.variable} pt-14  sm:px-2`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
